[package]
name = "native"
version = "0.1.0"
authors = ["Sam Phippen <samphippen@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rubyfmt"
crate-type = ["staticlib"]
