name: CI 2.6
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
    BUNDLE_PATH: /tmp/.bundle
    GEM_HOME: /tmp/.bundle
    GEM_PATH: /tmp/.bundle
    TERM: xterm256
    SCCACHE_DIR: /tmp/sccache
    RUSTC_WRAPPER: sccache

jobs:
  CI_26:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-2-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          /tmp/sccache
        key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          librubyfmt/ruby_checkout/ruby-2.6.6
        key: ${{ runner.os }}-ruby26-full
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y shellcheck build-essential ruby-dev bison

        SCCACHE_VERSION=0.2.15
        SCCACHE_FILE=sccache-v$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "https://github.com/mozilla/sccache/releases/download/v$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        chmod +x $SCCACHE_FILE/sccache
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - if: runner.os == 'macOS'
      run: |
        rustup component add clippy --toolchain stable-x86_64-apple-darwin
        rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
        brew install shellcheck sccache

        # Homebrew installs autoconf 2.71 which is incompatible with the
        # version of ruby embedded in this project, so force the installation
        # of the last known good version, 2.69.
        brew unlink autoconf
        brew tap-new $USER/local-autoconf
        brew extract --version=2.69 autoconf $USER/local-autoconf
        brew install autoconf@2.69
    - run: ./script/ci
