name: CI 2.6
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
    BUNDLE_PATH: /tmp/.bundle
    GEM_HOME: /tmp/.bundle
    GEM_PATH: /tmp/.bundle
    TERM: xterm256

jobs:
  CI_26:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          librubyfmt/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          librubyfmt/ruby_checkout/ruby-2.6.6/**/*.o
          librubyfmt/ruby_checkout/ruby-2.6.6/**/*.a
        key: ${{ runner.os }}-ruby26
    - uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.6
    - run: sudo apt-get install -y shellcheck build-essential ruby-dev bison

    - run: ./script/ci
